import 'quest.dart';

/// The quests, one after the other: from the first logs to level ten.
const List<Quest> questChain = [
  Quest(
    'wood',
    'Gather wood',
    'Punch or chop 8 logs',
    QuestGoal.collect,
    8,
    targets: ['oak_log', 'spruce_log'],
    xp: 20,
    items: {'apple': 2},
  ),
  Quest(
    'table',
    'Set up a workbench',
    'Craft a Crafting Table',
    QuestGoal.craft,
    1,
    targets: ['crafting_table'],
    xp: 20,
    items: {'torch': 4},
  ),
  Quest(
    'stone_pick',
    'Stone age',
    'Craft a Stone Pickaxe',
    QuestGoal.craft,
    1,
    targets: ['stone_pickaxe'],
    xp: 30,
    items: {'bread': 2},
  ),
  Quest(
    'sheep',
    'Dinner time',
    'Collect 3 raw meat',
    QuestGoal.collect,
    3,
    targets: ['raw_mutton', 'raw_beef', 'raw_pork', 'raw_chicken'],
    xp: 30,
    items: {'coal': 6},
  ),
  Quest(
    'night',
    'Night watch',
    'Slay 5 monsters',
    QuestGoal.kill,
    5,
    targets: ['zombie', 'skeleton', 'spider', 'slime', 'cave_slime', 'scorpion', 'snow_golem'],
    xp: 60,
    items: {'iron_ingot': 3, 'string': 3},
  ),
  Quest('coal', 'Miner', 'Mine 10 coal', QuestGoal.collect, 10, targets: ['coal'], xp: 40, items: {'lamp': 1}),
  Quest(
    'iron',
    'Iron will',
    'Smelt 5 iron ingots',
    QuestGoal.craft,
    5,
    targets: ['iron_ingot'],
    xp: 60,
    items: {'magic_dust': 2},
  ),
  Quest('level5', 'Adventurer', 'Reach level 5', QuestGoal.level, 5, xp: 80, items: {'health_potion': 2}),
  Quest(
    'glider',
    'Take to the skies',
    'Craft or find a Hang Glider',
    QuestGoal.have,
    1,
    targets: ['glider'],
    xp: 80,
    items: {'gold_ingot': 2},
  ),
  Quest(
    'troll',
    'Dungeon delver',
    'Slay a Cave Troll',
    QuestGoal.kill,
    1,
    targets: ['troll'],
    xp: 200,
    items: {'diamond': 3, 'crystal_staff': 1},
  ),
  Quest(
    'diamond',
    'Shine bright',
    'Mine 3 diamonds',
    QuestGoal.collect,
    3,
    targets: ['diamond'],
    xp: 150,
    items: {'diamond_sword': 1},
  ),
  Quest('level10', 'Hero of Dawnforge', 'Reach level 10', QuestGoal.level, 10, xp: 300, items: {'diamond_armor': 1}),
];
