import 'package:voxel_game/voxel_game.dart';

/// The game's blocks. THE ORDER IS THE SAVE CONTRACT: a chunk's edits are kept
/// by a block's index (`edits.bin`), so a row is appended, never moved or
/// removed. The kit puts air at 0, so `stone` is 1, as it always was.
///
/// Every block that is walked on names its recorded footsteps (`step:<kind>`,
/// `step_<kind>` in `gameSounds`): snow and ice crunch, sand and gravel hiss,
/// mud and clay squelch, what grows rustles, and the rest is hard ground. A
/// block whose material the kit would mishear (a metal one mined with a
/// pickaxe, wool, a lamp) says it (`sound:<family>`).
///
/// A block only the world makes (an open door, a stair turned, a lit wire, a
/// rail's curve, a crop growing) is no item (`holdable: false`); the item that
/// makes it is in `itemTable`.
const List<BlockType> blockTable = [
  BlockType.rgb(
    'stone',
    0.50,
    0.50,
    0.52,
    hardness: 3.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'cobblestone',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'dirt',
    0.55,
    0.38,
    0.24,
    hardness: 0.8,
    tool: 'shovel',
    turnsWith: {'hoe': 'farmland'},
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'grass',
    0.36,
    0.64,
    0.27,
    name: 'Grass Block',
    hardness: 0.9,
    tool: 'shovel',
    drop: 'dirt',
    turnsWith: {'hoe': 'farmland'},
    tags: {'step:forest'},
  ),
  BlockType.rgb('sand', 0.87, 0.81, 0.60, hardness: 0.7, tool: 'shovel', falls: true, tags: {'step:desert'}),
  BlockType.rgb(
    'water',
    0.20,
    0.42,
    0.78,
    alpha: 0.62,
    shape: BlockShape.liquid,
    solid: false,
    hardness: -1,
    drop: '',
    liquid: 'water',
    holdable: false,
  ),
  BlockType.rgb('oak_log', 0.43, 0.30, 0.17, hardness: 2.5, tool: 'axe', tags: {'step:lava'}),
  // Leaves drop an apple now and then; shears cut them whole (`MiningRules.cuts`).
  BlockType.rgb(
    'oak_leaves',
    0.25,
    0.52,
    0.19,
    hardness: 0.3,
    loot: LootTable([LootEntry('apple', 1, 1, 0.06)]),
    tags: {'leaves', 'step:forest', 'sound:plant'},
  ),
  BlockType.rgb(
    'gravel',
    0.56,
    0.54,
    0.51,
    hardness: 0.8,
    tool: 'shovel',
    falls: true,
    loot: LootTable.oneOf([LootEntry('flint', 1, 1, 0.15), LootEntry('gravel', 1, 1, 0.85)]),
    tags: {'step:desert'},
  ),
  BlockType.rgb('sandstone', 0.80, 0.74, 0.52, hardness: 1.5, tool: 'pickaxe', tier: 1, tags: {'step:desert'}),
  BlockType.rgb('snow', 0.94, 0.95, 0.98, hardness: 0.4, tool: 'shovel', tags: {'step:snow'}),
  BlockType.rgb('spruce_log', 0.30, 0.20, 0.12, hardness: 2.5, tool: 'axe', tags: {'step:lava'}),
  BlockType.rgb(
    'spruce_leaves',
    0.17,
    0.37,
    0.23,
    hardness: 0.3,
    drop: '',
    tags: {'leaves', 'step:forest', 'sound:plant'},
  ),
  BlockType.rgb(
    'cactus',
    0.29,
    0.56,
    0.25,
    hardness: 0.5,
    support: Support.below(on: {'sand', 'cactus'}),
    tags: {'step:forest', 'sound:plant'},
  ),
  BlockType.rgb(
    'coal_ore',
    0.30,
    0.30,
    0.31,
    hardness: 3.5,
    tool: 'pickaxe',
    tier: 1,
    drop: 'coal',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'iron_ore',
    0.66,
    0.54,
    0.46,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 2,
    drop: 'raw_iron',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'gold_ore',
    0.78,
    0.66,
    0.30,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 3,
    drop: 'raw_gold',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'diamond_ore',
    0.50,
    0.85,
    0.85,
    hardness: 5.0,
    tool: 'pickaxe',
    tier: 3,
    drop: 'diamond',
    tags: {'step:lava'},
  ),
  BlockType.rgb('bedrock', 0.22, 0.22, 0.24, hardness: -1, drop: '', tags: {'step:lava'}),
  BlockType.rgb('oak_planks', 0.72, 0.56, 0.33, hardness: 2.0, tool: 'axe', tags: {'step:lava'}),
  BlockType.rgb('cobblestone', 0.44, 0.44, 0.45, hardness: 3.0, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  BlockType.rgb('lamp', 0.98, 0.88, 0.50, hardness: 0.5, light: 15, tags: {'step:lava', 'sound:glass'}),
  // A station: the recipes that name it are crafted at it.
  BlockType.rgb('crafting_table', 0.62, 0.44, 0.24, hardness: 2.5, tool: 'axe', tags: {'step:lava'}),
  BlockType.rgb('glass', 0.80, 0.92, 0.97, alpha: 0.35, hardness: 0.4, drop: '', tags: {'step:lava'}),
  BlockType.rgb('bricks', 0.66, 0.31, 0.26, hardness: 3.0, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  BlockType.rgb('stone_bricks', 0.47, 0.47, 0.50, hardness: 3.0, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  BlockType.rgb('mossy_stone_bricks', 0.40, 0.50, 0.40, hardness: 3.0, tool: 'pickaxe', tier: 1, tags: {'step:forest'}),
  // Tall grass now and then gives a seed, or a string.
  BlockType.rgb(
    'tall_grass',
    0.40,
    0.68,
    0.28,
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    support: Support.below(),
    loot: LootTable.oneOf([LootEntry('wheat_seeds', 1, 1, 0.35), LootEntry('string', 1, 1, 0.0975)]),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'flower_red',
    0.88,
    0.24,
    0.24,
    name: 'Red Flower',
    shape: BlockShape.flower,
    solid: false,
    hardness: 0.0,
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'flower_yellow',
    0.94,
    0.84,
    0.26,
    name: 'Yellow Flower',
    shape: BlockShape.flower,
    solid: false,
    hardness: 0.0,
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'lava',
    0.98,
    0.45,
    0.10,
    alpha: 0.92,
    shape: BlockShape.liquid,
    solid: false,
    hardness: -1,
    drop: '',
    light: 13,
    liquid: 'lava',
    holdable: false,
  ),
  BlockType.rgb('clay', 0.62, 0.64, 0.70, hardness: 0.8, tool: 'shovel', tags: {'step:swamp'}),
  BlockType.rgb(
    'torch',
    0.98,
    0.78,
    0.35,
    shape: BlockShape.torch,
    solid: false,
    hardness: 0.0,
    light: 13,
    support: Support.below(),
    onWall: 'wall_torch',
    tags: {'step:forest'},
  ),
  BlockType.rgb('chest', 0.58, 0.40, 0.20, hardness: 2.5, tool: 'axe', storage: Storage(), tags: {'step:lava'}),
  BlockType.rgb(
    'furnace',
    0.38,
    0.38,
    0.41,
    hardness: 3.5,
    tool: 'pickaxe',
    tier: 1,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb('wool', 0.93, 0.93, 0.92, hardness: 0.8, tags: {'step:forest', 'sound:plant'}),
  BlockType.rgb('spruce_planks', 0.50, 0.36, 0.22, hardness: 2.0, tool: 'axe', tags: {'step:lava'}),
  BlockType.rgb(
    'dead_bush',
    0.55,
    0.42,
    0.24,
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    drop: 'stick',
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'mushroom',
    0.75,
    0.35,
    0.30,
    shape: BlockShape.flower,
    solid: false,
    hardness: 0.0,
    light: 2,
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'gold_block',
    0.95,
    0.80,
    0.30,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 3,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'iron_block',
    0.82,
    0.82,
    0.84,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 2,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'diamond_block',
    0.45,
    0.90,
    0.88,
    hardness: 5.0,
    tool: 'pickaxe',
    tier: 3,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb('ice', 0.70, 0.85, 0.98, alpha: 0.75, hardness: 0.5, tool: 'pickaxe', drop: '', tags: {'step:snow'}),
  BlockType.rgb(
    'dark_stone',
    0.33,
    0.33,
    0.37,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'cobblestone',
    tags: {'step:lava'},
  ),
  BlockType.rgb('bone_block', 0.88, 0.86, 0.76, hardness: 2.0, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  // A use sets the spawn; at night, with every player in bed, the night passes.
  BlockType.rgb('bed', 0.85, 0.25, 0.30, hardness: 0.5, bed: true, tags: {'step:lava', 'sound:wood'}),
  // Wheat: seeds on farmland, three stages in the light, the last one harvested.
  BlockType.rgb(
    'wheat_0',
    0.45,
    0.70,
    0.30,
    name: 'Wheat Sprout',
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    drop: 'wheat_seeds',
    support: Support.below(on: {'farmland'}),
    grows: Growth('wheat_1', seconds: 45),
    holdable: false,
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'wheat_1',
    0.60,
    0.72,
    0.30,
    name: 'Young Wheat',
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    drop: 'wheat_seeds',
    support: Support.below(on: {'farmland'}),
    grows: Growth('wheat_2', seconds: 45),
    holdable: false,
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'wheat_2',
    0.85,
    0.75,
    0.30,
    name: 'Wheat',
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    support: Support.below(on: {'farmland'}),
    loot: LootTable([LootEntry('wheat', 1, 3, 1.0), LootEntry('wheat_seeds', 1, 2, 1.0)]),
    holdable: false,
    tags: {'step:forest'},
  ),
  BlockType.rgb('farmland', 0.40, 0.27, 0.16, hardness: 0.8, tool: 'shovel', drop: 'dirt', tags: {'step:lava'}),
  BlockType.rgb(
    'spawner',
    0.20,
    0.12,
    0.28,
    name: 'Monster Spawner',
    hardness: 5.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'magic_dust',
    light: 4,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb('tnt', 0.85, 0.20, 0.15, name: 'TNT', hardness: 0.0, tags: {'step:lava'}),
  BlockType.rgb(
    'ladder',
    0.60,
    0.45,
    0.25,
    shape: BlockShape.ladder,
    solid: false,
    opaque: false,
    hardness: 0.4,
    tool: 'axe',
    tags: {'step:lava'},
  ),
  // A door: two high, across the way the placer looks, opened and closed with use.
  BlockType.rgb(
    'door_z',
    0.62,
    0.45,
    0.25,
    name: 'Door',
    shape: BlockShape.panelZ,
    opaque: false,
    hardness: 1.0,
    tool: 'axe',
    drop: 'door',
    tall: true,
    support: Support.below(),
    facing: Facing.axis(x: 'door_x', z: 'door_z'),
    usedInto: 'door_z_open',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'door_x',
    0.62,
    0.45,
    0.25,
    name: 'Door',
    shape: BlockShape.panelX,
    opaque: false,
    hardness: 1.0,
    tool: 'axe',
    drop: 'door',
    tall: true,
    support: Support.below(),
    usedInto: 'door_x_open',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'door_z_open',
    0.62,
    0.45,
    0.25,
    name: 'Open Door',
    shape: BlockShape.panelX,
    solid: false,
    opaque: false,
    hardness: 1.0,
    tool: 'axe',
    drop: 'door',
    tall: true,
    support: Support.below(),
    usedInto: 'door_z',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'door_x_open',
    0.62,
    0.45,
    0.25,
    name: 'Open Door',
    shape: BlockShape.panelZ,
    solid: false,
    opaque: false,
    hardness: 1.0,
    tool: 'axe',
    drop: 'door',
    tall: true,
    support: Support.below(),
    usedInto: 'door_x',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'wall_torch',
    0.98,
    0.78,
    0.35,
    shape: BlockShape.wallTorch,
    solid: false,
    hardness: 0.0,
    drop: 'torch',
    light: 13,
    support: Support.side(),
    holdable: false,
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'enchanting_table',
    0.38,
    0.18,
    0.55,
    hardness: 3.0,
    tool: 'pickaxe',
    tier: 1,
    light: 7,
    tags: {'step:lava', 'sound:glass'},
  ),
  BlockType.rgb(
    'brewing_stand',
    0.30,
    0.22,
    0.30,
    hardness: 2.0,
    tool: 'pickaxe',
    light: 3,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'waypoint',
    0.35,
    0.75,
    0.95,
    hardness: 3.0,
    tool: 'pickaxe',
    tier: 1,
    light: 10,
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb(
    'oak_slab',
    0.72,
    0.56,
    0.33,
    shape: BlockShape.slab,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'stone_slab',
    0.50,
    0.50,
    0.52,
    shape: BlockShape.slab,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'cobblestone_slab',
    0.44,
    0.44,
    0.45,
    shape: BlockShape.slab,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'oak_fence',
    0.43,
    0.30,
    0.17,
    shape: BlockShape.fence,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    tags: {'step:lava'},
  ),
  // Stairs climb away from whoever places them: four blocks behind one item.
  BlockType.rgb(
    'oak_stairs_n',
    0.72,
    0.56,
    0.33,
    name: 'Oak Stairs',
    shape: BlockShape.stairsN,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    drop: 'oak_stairs',
    facing: Facing.compass(north: 'oak_stairs_n', east: 'oak_stairs_e', south: 'oak_stairs_s', west: 'oak_stairs_w'),
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'oak_stairs_e',
    0.72,
    0.56,
    0.33,
    name: 'Oak Stairs',
    shape: BlockShape.stairsE,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    drop: 'oak_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'oak_stairs_s',
    0.72,
    0.56,
    0.33,
    name: 'Oak Stairs',
    shape: BlockShape.stairsS,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    drop: 'oak_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'oak_stairs_w',
    0.72,
    0.56,
    0.33,
    name: 'Oak Stairs',
    shape: BlockShape.stairsW,
    opaque: false,
    hardness: 2.0,
    tool: 'axe',
    drop: 'oak_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'stone_stairs_n',
    0.50,
    0.50,
    0.52,
    name: 'Stone Stairs',
    shape: BlockShape.stairsN,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'stone_stairs',
    facing: Facing.compass(
      north: 'stone_stairs_n',
      east: 'stone_stairs_e',
      south: 'stone_stairs_s',
      west: 'stone_stairs_w',
    ),
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'stone_stairs_e',
    0.50,
    0.50,
    0.52,
    name: 'Stone Stairs',
    shape: BlockShape.stairsE,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'stone_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'stone_stairs_s',
    0.50,
    0.50,
    0.52,
    name: 'Stone Stairs',
    shape: BlockShape.stairsS,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'stone_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'stone_stairs_w',
    0.50,
    0.50,
    0.52,
    name: 'Stone Stairs',
    shape: BlockShape.stairsW,
    opaque: false,
    hardness: 2.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'stone_stairs',
    holdable: false,
    tags: {'step:lava'},
  ),
  // The flowing form of each liquid: a source spreads into it and drains it when its feeder goes.
  BlockType.rgb(
    'water_flow',
    0.26,
    0.48,
    0.82,
    name: 'Water',
    alpha: 0.58,
    shape: BlockShape.liquid,
    solid: false,
    hardness: -1,
    drop: '',
    liquid: 'water',
    liquidSource: false,
    holdable: false,
  ),
  BlockType.rgb(
    'lava_flow',
    0.99,
    0.55,
    0.16,
    name: 'Lava',
    alpha: 0.92,
    shape: BlockShape.liquid,
    solid: false,
    hardness: -1,
    drop: '',
    light: 13,
    liquid: 'lava',
    liquidSource: false,
    holdable: false,
  ),
  // A body standing on it powers what it touches: the temple's trap lights the TNT under it.
  BlockType.rgb(
    'pressure_plate',
    0.24,
    0.20,
    0.18,
    shape: BlockShape.slab,
    opaque: false,
    hardness: 1.0,
    tool: 'pickaxe',
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb('mud', 0.36, 0.26, 0.18, hardness: 0.8, tool: 'shovel', tags: {'step:swamp'}),
  BlockType.rgb(
    'reeds',
    0.55,
    0.72,
    0.38,
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb('jungle_log', 0.42, 0.30, 0.16, hardness: 2.0, tool: 'axe', tags: {'step:lava'}),
  BlockType.rgb(
    'vines',
    0.22,
    0.48,
    0.20,
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    drop: '',
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'fern',
    0.30,
    0.60,
    0.26,
    shape: BlockShape.cross,
    solid: false,
    hardness: 0.0,
    drop: '',
    support: Support.below(),
    tags: {'step:forest'},
  ),
  BlockType.rgb(
    'melon',
    0.45,
    0.68,
    0.25,
    hardness: 1.0,
    tool: 'axe',
    loot: LootTable([LootEntry('melon_slice', 3, 5, 1.0)]),
    tags: {'step:forest', 'sound:plant'},
  ),
  // Circuits (`gameSignals`): every powered state is a block of its own.
  BlockType.rgb(
    'redstone_ore',
    0.62,
    0.30,
    0.30,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 2,
    drop: 'redstone_dust',
    tags: {'step:lava'},
  ),
  BlockType.rgb(
    'lever_off',
    0.55,
    0.55,
    0.57,
    name: 'Lever',
    shape: BlockShape.torch,
    solid: false,
    hardness: 0.3,
    drop: 'lever',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb(
    'lever_on',
    0.95,
    0.25,
    0.20,
    name: 'Lever',
    shape: BlockShape.torch,
    solid: false,
    hardness: 0.3,
    drop: 'lever',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb(
    'button',
    0.66,
    0.66,
    0.68,
    shape: BlockShape.torch,
    solid: false,
    hardness: 0.3,
    support: Support.below(),
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb(
    'button_on',
    0.90,
    0.90,
    0.92,
    name: 'Button',
    shape: BlockShape.torch,
    solid: false,
    hardness: 0.3,
    drop: 'button',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:wood'},
  ),
  BlockType.rgb(
    'wire_off',
    0.45,
    0.10,
    0.10,
    name: 'Redstone Wire',
    shape: BlockShape.wire,
    solid: false,
    hardness: 0.0,
    drop: 'wire',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'wire_on',
    1.00,
    0.25,
    0.20,
    name: 'Redstone Wire',
    shape: BlockShape.wire,
    solid: false,
    hardness: 0.0,
    drop: 'wire',
    light: 3,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'redstone_lamp_off',
    0.45,
    0.32,
    0.22,
    name: 'Redstone Lamp',
    hardness: 0.5,
    drop: 'redstone_lamp',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'redstone_lamp_on',
    1.00,
    0.85,
    0.45,
    name: 'Redstone Lamp',
    hardness: 0.5,
    drop: 'redstone_lamp',
    light: 14,
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  // An iron door opens only while powered.
  BlockType.rgb(
    'iron_door_z',
    0.80,
    0.80,
    0.83,
    name: 'Iron Door',
    shape: BlockShape.panelZ,
    opaque: false,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'iron_door',
    tall: true,
    support: Support.below(),
    facing: Facing.axis(x: 'iron_door_x', z: 'iron_door_z'),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'iron_door_x',
    0.80,
    0.80,
    0.83,
    name: 'Iron Door',
    shape: BlockShape.panelX,
    opaque: false,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'iron_door',
    tall: true,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'iron_door_z_open',
    0.80,
    0.80,
    0.83,
    name: 'Open Iron Door',
    shape: BlockShape.panelX,
    solid: false,
    opaque: false,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'iron_door',
    tall: true,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'iron_door_x_open',
    0.80,
    0.80,
    0.83,
    name: 'Open Iron Door',
    shape: BlockShape.panelZ,
    solid: false,
    opaque: false,
    hardness: 4.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'iron_door',
    tall: true,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  // A piston pushes away from whoever places it; out, it is the grey block.
  BlockType.rgb(
    'piston_n',
    0.62,
    0.50,
    0.34,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    facing: Facing.compass(north: 'piston_n', east: 'piston_e', south: 'piston_s', west: 'piston_w'),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_e',
    0.62,
    0.50,
    0.34,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_s',
    0.62,
    0.50,
    0.34,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_w',
    0.62,
    0.50,
    0.34,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_n_on',
    0.50,
    0.50,
    0.53,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_e_on',
    0.50,
    0.50,
    0.53,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_s_on',
    0.50,
    0.50,
    0.53,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'piston_w_on',
    0.50,
    0.50,
    0.53,
    name: 'Piston',
    hardness: 1.5,
    tool: 'pickaxe',
    drop: 'piston',
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  // Rails: a rail laid turns to meet the rails beside it (a straight, a curve, a slope), and each drops a rail.
  BlockType.rgb(
    'rail_ns',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railNs,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_ew',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railEw,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_ne',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railNe,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_nw',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railNw,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_se',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSe,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_sw',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSw,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_slope_n',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSlopeN,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_slope_e',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSlopeE,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_slope_s',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSlopeS,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'rail_slope_w',
    0.60,
    0.60,
    0.64,
    name: 'Rail',
    shape: BlockShape.railSlopeW,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  // A powered rail runs the way the placer looks; a run of them is lit eight rails on from the power.
  BlockType.rgb(
    'powered_rail_ns',
    0.70,
    0.58,
    0.28,
    name: 'Powered Rail',
    shape: BlockShape.railNs,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'powered_rail',
    support: Support.below(),
    facing: Facing.axis(x: 'powered_rail_ew', z: 'powered_rail_ns'),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'powered_rail_ew',
    0.70,
    0.58,
    0.28,
    name: 'Powered Rail',
    shape: BlockShape.railEw,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'powered_rail',
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'powered_rail_ns_on',
    1.00,
    0.55,
    0.25,
    name: 'Powered Rail',
    shape: BlockShape.railNs,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'powered_rail',
    light: 4,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  BlockType.rgb(
    'powered_rail_ew_on',
    1.00,
    0.55,
    0.25,
    name: 'Powered Rail',
    shape: BlockShape.railEw,
    solid: false,
    opaque: false,
    hardness: 0.5,
    tool: 'pickaxe',
    drop: 'powered_rail',
    light: 4,
    support: Support.below(),
    holdable: false,
    tags: {'step:lava', 'sound:metal'},
  ),
  // The underworld: obsidian (the portal's frame), the portal itself, its rock, soul sand that slows a walker,
  // glowstone that lights its ceilings, quartz in its walls, the fortress's bricks and its core.
  BlockType.rgb('obsidian', 0.10, 0.06, 0.16, hardness: 15.0, tool: 'pickaxe', tier: 4, tags: {'step:lava'}),
  BlockType.rgb(
    'portal',
    0.55,
    0.15,
    0.95,
    alpha: 0.62,
    solid: false,
    opaque: false,
    hardness: -1,
    drop: '',
    light: 11,
    holdable: false,
    tags: {'sound:glass'},
  ),
  BlockType.rgb('hellstone', 0.42, 0.14, 0.12, hardness: 0.4, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  BlockType.rgb('soul_sand', 0.32, 0.24, 0.18, hardness: 0.5, tool: 'shovel', speed: 0.5, tags: {'step:desert'}),
  BlockType.rgb(
    'glowstone',
    0.98,
    0.85,
    0.45,
    hardness: 0.3,
    light: 15,
    loot: LootTable([LootEntry('glowstone_dust', 2, 4, 1.0)]),
    tags: {'step:lava', 'sound:glass'},
  ),
  BlockType.rgb(
    'nether_quartz_ore',
    0.62,
    0.36,
    0.34,
    name: 'Quartz Ore',
    hardness: 3.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'quartz',
    tags: {'step:lava'},
  ),
  BlockType.rgb('nether_brick', 0.20, 0.09, 0.11, hardness: 2.0, tool: 'pickaxe', tier: 1, tags: {'step:lava'}),
  BlockType.rgb(
    'fortress_core',
    0.45,
    0.10,
    0.70,
    hardness: 5.0,
    tool: 'pickaxe',
    tier: 1,
    drop: 'underworld_heart',
    light: 8,
    tags: {'step:lava'},
  ),
];
