import 'package:voxel_game/voxel_game.dart';

/// How things are made: by hand, or at a station (a block a recipe names:
/// the crafting table, the furnace, the brewing stand). Every furnace recipe
/// burns a coal.
const List<Recipe> recipeTable = [
  // By hand.
  Recipe('oak_planks', 4, {'oak_log': 1}),
  Recipe('spruce_planks', 4, {'spruce_log': 1}),
  Recipe('stick', 4, {'oak_planks': 2}),
  Recipe('stick', 4, {'spruce_planks': 2}),
  Recipe('crafting_table', 1, {'oak_planks': 4}),
  Recipe('crafting_table', 1, {'spruce_planks': 4}),
  Recipe('torch', 4, {'coal': 1, 'stick': 1}),
  Recipe('wooden_pickaxe', 1, {'oak_planks': 3, 'stick': 2}),
  Recipe('wooden_axe', 1, {'oak_planks': 3, 'stick': 2}),
  Recipe('wooden_shovel', 1, {'oak_planks': 1, 'stick': 2}),
  Recipe('wooden_sword', 1, {'oak_planks': 2, 'stick': 1}),
  Recipe('ladder', 3, {'stick': 7}),
  Recipe('oak_slab', 6, {'oak_planks': 3}),
  Recipe('stone_slab', 6, {'stone': 3}),
  Recipe('cobblestone_slab', 6, {'cobblestone': 3}),
  Recipe('mushroom_stew', 1, {'mushroom': 2}),
  Recipe('lever', 1, {'stick': 1, 'cobblestone': 1}),
  Recipe('button', 1, {'stone': 1}),
  Recipe('wire', 4, {'redstone_dust': 1}),
  Recipe('bread', 1, {'wheat': 3}),
  Recipe('wooden_hoe', 1, {'oak_planks': 2, 'stick': 2}),
  // The crafting table.
  Recipe('stone_pickaxe', 1, {'cobblestone': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('stone_axe', 1, {'cobblestone': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('stone_shovel', 1, {'cobblestone': 1, 'stick': 2}, station: 'crafting_table'),
  Recipe('stone_sword', 1, {'cobblestone': 2, 'stick': 1}, station: 'crafting_table'),
  Recipe('iron_pickaxe', 1, {'iron_ingot': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('iron_axe', 1, {'iron_ingot': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('iron_shovel', 1, {'iron_ingot': 1, 'stick': 2}, station: 'crafting_table'),
  Recipe('iron_sword', 1, {'iron_ingot': 2, 'stick': 1}, station: 'crafting_table'),
  Recipe('diamond_pickaxe', 1, {'diamond': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('diamond_axe', 1, {'diamond': 3, 'stick': 2}, station: 'crafting_table'),
  Recipe('diamond_shovel', 1, {'diamond': 1, 'stick': 2}, station: 'crafting_table'),
  Recipe('diamond_sword', 1, {'diamond': 2, 'stick': 1}, station: 'crafting_table'),
  Recipe('dagger', 1, {'cobblestone': 1, 'stick': 1}, station: 'crafting_table'),
  Recipe('iron_dagger', 1, {'iron_ingot': 2, 'stick': 1}, station: 'crafting_table'),
  Recipe('bow', 1, {'stick': 3, 'string': 3}, station: 'crafting_table'),
  Recipe('longbow', 1, {'stick': 3, 'string': 3, 'iron_ingot': 1}, station: 'crafting_table'),
  Recipe('arrow', 6, {'flint': 1, 'stick': 1, 'feather': 1}, station: 'crafting_table'),
  Recipe('staff', 1, {'stick': 2, 'magic_dust': 1}, station: 'crafting_table'),
  Recipe('crystal_staff', 1, {'stick': 2, 'diamond': 1, 'magic_dust': 3}, station: 'crafting_table'),
  Recipe('furnace', 1, {'cobblestone': 8}, station: 'crafting_table'),
  Recipe('chest', 1, {'oak_planks': 8}, station: 'crafting_table'),
  Recipe('glider', 1, {'wool': 6, 'stick': 4, 'string': 2}, station: 'crafting_table'),
  Recipe('leather_armor', 1, {'leather': 8}, station: 'crafting_table'),
  Recipe('iron_armor', 1, {'iron_ingot': 12}, station: 'crafting_table'),
  Recipe('diamond_armor', 1, {'diamond': 12}, station: 'crafting_table'),
  Recipe('lamp', 1, {'glass': 1, 'coal': 2, 'magic_dust': 1}, station: 'crafting_table'),
  Recipe('stone_bricks', 4, {'stone': 4}, station: 'crafting_table'),
  Recipe('wool', 1, {'string': 4}, station: 'crafting_table'),
  Recipe('bone_block', 1, {'bone': 9}, station: 'crafting_table'),
  Recipe('iron_block', 1, {'iron_ingot': 9}, station: 'crafting_table'),
  Recipe('gold_block', 1, {'gold_ingot': 9}, station: 'crafting_table'),
  Recipe('diamond_block', 1, {'diamond': 9}, station: 'crafting_table'),
  Recipe('tnt', 1, {'gunpowder': 5, 'sand': 4}, station: 'crafting_table'),
  Recipe('bed', 1, {'wool': 3, 'oak_planks': 3}, station: 'crafting_table'),
  Recipe('door', 1, {'oak_planks': 6}, station: 'crafting_table'),
  Recipe('iron_door', 1, {'iron_ingot': 6}, station: 'crafting_table'),
  Recipe('redstone_lamp', 1, {'redstone_dust': 4, 'torch': 1}, station: 'crafting_table'),
  Recipe('piston', 1, {
    'oak_planks': 3,
    'cobblestone': 4,
    'iron_ingot': 1,
    'redstone_dust': 1,
  }, station: 'crafting_table'),
  Recipe('oak_fence', 3, {'stick': 4, 'oak_planks': 2}, station: 'crafting_table'),
  Recipe('oak_stairs', 4, {'oak_planks': 6}, station: 'crafting_table'),
  Recipe('stone_stairs', 4, {'stone_bricks': 6}, station: 'crafting_table'),
  Recipe('boat', 1, {'oak_planks': 5}, station: 'crafting_table'),
  Recipe('rail', 16, {'iron_ingot': 6, 'stick': 1}, station: 'crafting_table'),
  Recipe('powered_rail', 6, {'gold_ingot': 6, 'stick': 1, 'redstone_dust': 1}, station: 'crafting_table'),
  Recipe('minecart', 1, {'iron_ingot': 5}, station: 'crafting_table'),
  Recipe('enchanting_table', 1, {'diamond': 1, 'magic_dust': 4, 'stone_bricks': 4}, station: 'crafting_table'),
  Recipe('health_potion', 1, {'apple': 2, 'magic_dust': 1, 'glass': 1}, station: 'crafting_table'),
  Recipe('brewing_stand', 1, {'cobblestone': 3, 'glass': 1, 'magic_dust': 1}, station: 'crafting_table'),
  Recipe('glass_bottle', 3, {'glass': 1}, station: 'crafting_table'),
  Recipe('waypoint', 1, {'stone_bricks': 4, 'magic_dust': 2}, station: 'crafting_table'),
  Recipe('fishing_rod', 1, {'stick': 3, 'string': 2}, station: 'crafting_table'),
  Recipe('shears', 1, {'iron_ingot': 2}, station: 'crafting_table'),
  Recipe('bucket', 1, {'iron_ingot': 3}, station: 'crafting_table'),
  Recipe('flint_and_steel', 1, {'iron_ingot': 1, 'flint': 1}, station: 'crafting_table'),
  Recipe('glowstone', 1, {'glowstone_dust': 4}, station: 'crafting_table'),
  // The brewing stand.
  Recipe('speed_potion', 1, {'glass_bottle': 1, 'wheat': 1, 'feather': 1}, station: 'brewing_stand'),
  Recipe('regen_potion', 1, {'glass_bottle': 1, 'apple': 1, 'magic_dust': 1}, station: 'brewing_stand'),
  Recipe('strength_potion', 1, {'glass_bottle': 1, 'spider_eye': 1, 'gunpowder': 1}, station: 'brewing_stand'),
  Recipe('resistance_potion', 1, {'glass_bottle': 1, 'iron_ingot': 1, 'slime_ball': 1}, station: 'brewing_stand'),
  Recipe('haste_potion', 1, {'glass_bottle': 1, 'coal': 2, 'gem_shard': 1}, station: 'brewing_stand'),
  Recipe('antidote', 1, {'glass_bottle': 1, 'mushroom': 1, 'bone': 1}, station: 'brewing_stand'),
  Recipe('health_potion', 1, {'glass_bottle': 1, 'apple': 1, 'magic_dust': 1}, station: 'brewing_stand'),
  // The furnace.
  Recipe('bricks', 4, {'clay': 4}, station: 'furnace'),
  Recipe('iron_ingot', 1, {'raw_iron': 1, 'coal': 1}, station: 'furnace'),
  Recipe('gold_ingot', 1, {'raw_gold': 1, 'coal': 1}, station: 'furnace'),
  Recipe('glass', 1, {'sand': 1, 'coal': 1}, station: 'furnace'),
  Recipe('stone', 1, {'cobblestone': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_beef', 1, {'raw_beef': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_pork', 1, {'raw_pork': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_mutton', 1, {'raw_mutton': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_chicken', 1, {'raw_chicken': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_fish', 1, {'raw_fish': 1, 'coal': 1}, station: 'furnace'),
  Recipe('cooked_salmon', 1, {'raw_salmon': 1, 'coal': 1}, station: 'furnace'),
];
