import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_scene/scene.dart' show Node;
import 'package:vector_math/vector_math.dart';
import 'package:voxel_engine/content.dart';
import 'package:voxel_engine/core.dart';
import 'package:voxel_scene/voxel_scene.dart';
import 'package:voxel_engine/worldgen.dart';

/// Called after a block changes: the cell, what was there, what is there now.
typedef BlockChangedListener = void Function(IVec3 cell, int oldId, int newId);

/// How one liquid kind flows in a [GameWorld], and how it looks from inside.
class LiquidSpec {
  /// A liquid stepping every [period] seconds, spreading [reach] cells from a
  /// source, washing the screen at [tint] opacity and closing the view in to
  /// [haze] while the camera is in it.
  const LiquidSpec({this.period = 0.25, this.reach = 4, this.tint = 0.25, this.haze = water})
    : assert(tint >= 0.0 && tint <= 1.0, 'LiquidSpec.tint is an opacity, 0..1');

  /// Water's murk: a deep blue, 63 % at 20 m, darkening with the sky.
  static const Haze water = Haze(0x081F47, 0.05, followsSky: true);

  /// Lava's glare: orange, 70 % a metre off.
  static const Haze lava = Haze(0xBF3805, 1.2);

  /// What a kind not in `VoxelGameSpec.liquids` does: lava is slow, short and
  /// thick, any other flows like water.
  static LiquidSpec defaultFor(String kind) =>
      kind == 'lava' ? const LiquidSpec(period: 0.6, reach: 2, tint: 0.55, haze: lava) : const LiquidSpec();

  /// Seconds between steps.
  final double period;

  /// Cells a source feeds sideways.
  final int reach;

  /// How opaque the wash over the screen is while the camera is in it, in the
  /// colour of the block it is in (the default HUD's); 0 for none.
  final double tint;

  /// The fog around the camera while it is in it, or null for the sky's.
  final Haze? haze;
}

/// The world of a game: blocks streamed around a focus point, generated from
/// a [WorldGenSpec] per dimension, meshed on worker isolates (or on this one,
/// headless), drawn by a [VoxelChunkView], with liquids that flow. What
/// bodies, rays and paths read ([VoxelQuery]) and what tools write
/// ([VoxelEditor]).
///
/// One dimension streams at a time ([dimension], 0 first); the edits of the
/// others wait for it to come back ([switchDimension], [storeEditIn]).
class GameWorld implements VoxelEditor {
  GameWorld._(
    this.blocks,
    this.generators,
    this._jobs, {
    required int loadRadius,
    required this.headless,
    Map<String, LiquidSpec> liquids = const {},
  }) {
    _view = headless ? null : VoxelChunkView();
    _streamer = ChunkStreamer(table: blocks.table, sink: _view ?? _NoSink(), loadRadius: loadRadius);
    flow = LiquidFlow(
      table: blocks.table,
      rules: [
        for (final kind in blocks.liquidKinds)
          _hasFlowingForm(kind)
              ? LiquidRule(
                  flowingId: blocks.flowingOf(kind),
                  period: (liquids[kind] ?? LiquidSpec.defaultFor(kind)).period,
                  reach: (liquids[kind] ?? LiquidSpec.defaultFor(kind)).reach,
                )
              // A liquid without a flowing form stays where it is put.
              : LiquidRule(flowingId: blocks.indexOf(kind), period: double.infinity, reach: 0),
      ],
      canEnter: blocks.isReplaceable,
    );
  }

  /// A world of [blocks] whose dimension `d` is generated by `dimensions[d]`
  /// under [seed], meshed on a pool of worker isolates; call [start] before
  /// the first [update].
  factory GameWorld(
    BlockRegistry<BlockType> blocks,
    List<WorldGenSpec> dimensions,
    int seed, {
    int loadRadius = 6,
    Map<String, LiquidSpec> liquids = const {},
  }) {
    final generators = DimensionGenerator(dimensions, blocks.ids, seed);
    return GameWorld._(blocks, generators, null, loadRadius: loadRadius, headless: false, liquids: liquids);
  }

  /// The same world with no renderer and no isolates: chunks are generated and
  /// meshed on this isolate as they are asked for. For tests and servers.
  factory GameWorld.headless(
    BlockRegistry<BlockType> blocks,
    List<WorldGenSpec> dimensions,
    int seed, {
    int loadRadius = 2,
    Map<String, LiquidSpec> liquids = const {},
  }) {
    final generators = DimensionGenerator(dimensions, blocks.ids, seed);
    return GameWorld._(
      blocks,
      generators,
      _LocalJobs(generators, blocks.table),
      loadRadius: loadRadius,
      headless: true,
      liquids: liquids,
    );
  }

  bool _hasFlowingForm(String kind) => blocks.types.any((t) => t.liquid == kind && !t.liquidSource);

  /// The game's blocks.
  final BlockRegistry<BlockType> blocks;

  /// Every dimension's generator.
  final DimensionGenerator generators;

  /// The generator of the dimension streaming, for terrain questions (height,
  /// biome, structures).
  SpecGenerator get generator => generators[dimension];

  /// The dimension streaming, numbered as the generators are.
  int get dimension => _streamer.dimension;

  /// Whether there is no renderer and no worker pool.
  final bool headless;

  final ChunkJobs? _jobs;
  VoxelChunkView? _view;
  late final ChunkStreamer _streamer;
  ChunkWorkerPool? _pool;

  /// The liquids' flow; host-only in a networked game ([LiquidFlow.enabled]).
  late final LiquidFlow flow;

  final List<BlockChangedListener> _listeners = [];

  /// The chunk nodes to add to the scene; null headless.
  Node? get root => _view?.root;

  /// Starts the worker isolates (none headless). The factory is built in a
  /// static so the closure sent to them captures only sendable values.
  Future<void> start() async {
    final local = _jobs;
    if (local != null) {
      _streamer.jobs = local;
      return;
    }
    _pool?.dispose();
    final pool = ChunkWorkerPool(
      ChunkWorkerConfig(
        generator: _factory([for (final g in generators.dimensions) g.spec], blocks.ids, generators.seed),
        table: blocks.table,
      ),
    );
    await pool.start();
    _pool = pool;
    _streamer.jobs = pool;
  }

  static ChunkGeneratorFactory _factory(List<WorldGenSpec> specs, Map<String, int> ids, int seed) =>
      () => DimensionGenerator(specs, ids, seed);

  /// Stops the worker isolates.
  void dispose() {
    _pool?.dispose();
    _pool = null;
    _streamer.jobs = null;
  }

  /// How far chunks are kept around the focus, in chunks. A change takes
  /// at once: a nearer window drops what lies past it now, a further one
  /// streams what it gained from the next [update].
  int get loadRadius => _streamer.loadRadius;

  set loadRadius(int value) {
    if (value < 1) throw ArgumentError.value(value, 'loadRadius', 'at least one chunk');
    _streamer
      ..loadRadius = value
      ..unloadRadius = value + 2
      ..trimWindow()
      ..refresh();
  }

  /// Streams the window around [focus], lands the jobs that finished and
  /// rebuilds, within the view's budget, the regions they changed, the nearest
  /// first; once a frame.
  void update(Vector3 focus) {
    final centre = ChunkStreamer.chunkOfXZ(focus.x.floor(), focus.z.floor());
    _streamer.updateAround(centre);
    _streamer.update();
    _view?.rebuild(centre);
  }

  /// Advances the liquids by [dt]; once a simulation step.
  void tickFlow(double dt) => flow.tick(this, dt);

  /// Whether nothing is waiting to be generated, meshed or drawn.
  bool get isIdle {
    final view = _view;
    return _streamer.isIdle && (view == null || view.pendingRegions == 0);
  }

  /// How many chunks have a mesh.
  int get meshCount => _streamer.meshCount;

  /// How many chunks are loaded.
  int get loadedChunkCount => _streamer.loadedChunkCount;

  /// Chunk meshes built since the world started, remeshes included.
  int get chunksBuilt => _streamer.chunksBuilt;

  /// Faces in every mesh built since the world started.
  int get facesEmitted => _streamer.facesEmitted;

  /// How bright the sky's baked light shows (1 noon, ~0.35 night).
  void setSkyIntensity(double value) => _view?.setSkyIntensity(value);

  @override
  VoxelBlockTable get table => blocks.table;

  @override
  int getBlockXYZ(int x, int y, int z) => _streamer.getBlockXYZ(x, y, z);

  /// The block at [cell].
  int getBlock(IVec3 cell) => _streamer.getBlockXYZ(cell.x, cell.y, cell.z);

  /// The id (name) of the block at [cell].
  String blockNameAt(IVec3 cell) => blocks.idOf(getBlock(cell));

  /// Whether [cell]'s chunk is loaded.
  bool isLoaded(IVec3 cell) => _streamer.chunkAtXZ(cell.x, cell.z) != null;

  /// Whether the block at [cell] stops a body; below the world counts.
  bool isSolid(IVec3 cell) => cell.y < 0 || blocks.table.isSolid(getBlock(cell));

  /// (sky, block) light of [cell], 0..15 each.
  CellLight lightAt(IVec3 cell) => _streamer.lightAt(cell);

  @override
  bool setBlock(IVec3 cell, int id) {
    final old = getBlock(cell);
    if (!_streamer.setBlock(cell, id)) return false;
    flow.touch(this, cell, old, id);
    for (final l in List.of(_listeners)) {
      l(cell, old, id);
    }
    return true;
  }

  /// Writes [id] at [cell] now, or when its chunk generates if it is not
  /// loaded: an edit that must not be lost (another player's).
  void storeEdit(IVec3 cell, int id) {
    if (isLoaded(cell)) {
      setBlock(cell, id);
    } else {
      _streamer.storeEdit(cell, id);
    }
  }

  /// [storeEdit] in dimension [d]: an edit of a dimension not streaming
  /// waits in its delta and lands when that dimension streams the chunk.
  void storeEditIn(int d, IVec3 cell, int id) {
    _checkDimension(d);
    if (d == dimension) {
      storeEdit(cell, id);
    } else {
      _streamer.storeEditElsewhere(d, cell, id);
    }
  }

  /// Cells edited in dimension [d].
  int editCountIn(int d) => _streamer.editCountIn(d);

  /// Streams dimension [d] from now on: every chunk, mesh and light of the
  /// one streaming goes (its edits kept), the liquids forget what they were
  /// doing, and the window fills again around the next [update]'s focus.
  /// Throws for the dimension streaming and one the world has not.
  void switchDimension(int d) {
    _checkDimension(d);
    if (d == dimension) throw ArgumentError.value(d, 'd', 'the world streams it already');
    _streamer.switchDimension(d);
    flow.clear();
  }

  void _checkDimension(int d) {
    if (d < 0 || d >= generators.dimensions.length) {
      throw ArgumentError.value(d, 'd', 'the world has ${generators.dimensions.length} dimensions');
    }
  }

  /// Where a body arriving at column ([x], [z]) stands, its feet's cell: the
  /// spot with two clear cells (neither solid nor liquid) over firm ground
  /// (solid, not liquid) nearest the generator's surface, in that column or,
  /// failing it, the nearest columns around it, four out at most. Where there
  /// is none, a pocket is carved at the column's surface, above the sea: the
  /// dimension's stone to stand on, two cells of air. Read and carved in the
  /// loaded world: the chunks around the column must be loaded.
  IVec3 arrivalAt(int x, int z) {
    for (var r = 0; r <= 4; r++) {
      for (var dz = -r; dz <= r; dz++) {
        for (var dx = -r; dx <= r; dx++) {
          if (dx.abs() != r && dz.abs() != r) continue;
          final cx = x + dx, cz = z + dz;
          final aim = generator.surfaceHeight(cx, cz);
          for (var d = 0; d < ChunkSize.sizeY; d++) {
            for (final y in d == 0 ? [aim] : [aim - d, aim + d]) {
              if (y >= 1 && y < ChunkSize.sizeY - 1 && _canStand(cx, y, cz)) return IVec3(cx, y, cz);
            }
          }
        }
      }
    }
    final spec = generator.spec;
    final y = math.max(generator.surfaceHeight(x, z), spec.seaLevel + 1).clamp(1, ChunkSize.sizeY - 3);
    setBlockNamed(IVec3(x, y - 1, z), spec.stone);
    setBlock(IVec3(x, y, z), BlockRegistry.air);
    setBlock(IVec3(x, y + 1, z), BlockRegistry.air);
    return IVec3(x, y, z);
  }

  bool _canStand(int x, int y, int z) {
    bool clear(int y) {
      final id = getBlockXYZ(x, y, z);
      return !blocks.table.isSolid(id) && !blocks[id].isLiquid;
    }

    final floor = getBlockXYZ(x, y - 1, z);
    return clear(y) && clear(y + 1) && blocks.table.isSolid(floor) && !blocks[floor].isLiquid;
  }

  /// Writes block [name] at [cell]; false when its chunk is not loaded.
  bool setBlockNamed(IVec3 cell, String name) => setBlock(cell, blocks.indexOf(name));

  /// Every edit made to the generated world, by dimension and chunk: what a
  /// save keeps. Live maps; copy before changing.
  EditsByDimension get edits => _streamer.editsByDimension;

  /// Replaces the edits (a save read back); call before the first [update].
  void replaceEdits(EditsByDimension all) => _streamer.replaceEdits(all);

  /// Cells edited so far.
  int get editCount => _streamer.editCount;

  /// Calls [listener] after every block change.
  void addListener(BlockChangedListener listener) => _listeners.add(listener);

  /// Stops calling [listener].
  void removeListener(BlockChangedListener listener) => _listeners.remove(listener);

  /// The first air cell above the highest solid block of column ([x], [z])
  /// among loaded chunks, or the generator's surface where the chunk is not
  /// loaded yet.
  int groundHeight(int x, int z) {
    final chunk = _streamer.chunkAtXZ(x, z);
    if (chunk == null) return generator.surfaceHeight(x, z);
    final lx = x & ChunkSize.maskX;
    final lz = z & ChunkSize.maskZ;
    for (var y = ChunkSize.sizeY - 1; y >= 0; y--) {
      if (blocks.table.isSolid(chunk[ChunkSize.index(lx, y, lz)])) return y + 1;
    }
    return 0;
  }
}

class _NoSink implements ChunkMeshSink {
  @override
  void apply(ChunkPos pos, ChunkMeshResult result) {}

  @override
  void remove(ChunkPos pos) {}
}

class _LocalJobs implements ChunkJobs {
  _LocalJobs(this.generator, VoxelBlockTable table) : _mesher = table.mesher();

  final DimensionGenerator generator;
  final ChunkMesher _mesher;

  @override
  Future<Uint8List> generate(int cx, int cz, [int dimension = 0]) =>
      Future.value(generator.generateIn(cx, cz, dimension));

  @override
  Future<ChunkMeshResult> mesh(int cx, int cz, List<Uint8List?> ring) => Future.value(_mesher.build(cx, cz, ring));
}
